name: "Label Issues"
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.0
        with:
          configuration-path: .github/config/labels.yml
          repo-token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}